/**
 * Remove the first and last line of a file - which strips unfortunate
 * JS formatting that esbuild puts out.
 * @param filename
 * @returns
 */

const decoder = new TextDecoder("utf-8");
const encoder = new TextEncoder("utf-8");

function fileStripper(filename: string) {
  const fileContent = Deno.readFileSync(filename);
  let lines = decoder.decode(fileContent).split("\n");
  lines = lines.slice(1, -1);
  if (lines[lines.length - 1].trim().startsWith("})();")) {
    lines = lines.slice(0, -1);
  }
  return "/* Do not edit - autogenerated */\n" + lines.join("\n");
}

/**
 * Process all files in a directory using fileStripper and rewrite them.
 * @param dirPath
 */
function processDirectory(dirPath: string) {
  const files = Deno.readDirSync(dirPath);
  for (const file of files) {
    const filePath = `${dirPath}/${file.name}`;
    if (
      filePath.indexOf(".d.js") === -1 &&
      Deno.statSync(filePath).isFile
    ) {
      console.log("Processing", filePath);
      const strippedContent = fileStripper(filePath);
      Deno.writeFileSync(filePath, encoder.encode(strippedContent));
    }
  }
}

processDirectory("static/sketches");
