import { ArtPiece } from "@lib/types.d.ts";

export const artPieces: ArtPiece[] = [
  {
    // "id": 1,
    title: "Neon Bee",
    description: "A neon bee sculpture.",
    media: "Virtual Neon",
    url: "bees/bee-s-e120.jpg",
    hash: "",
    mime: "image/jpeg",
    width: 1000,
    height: 628,
    slug: "neon-bee",
    galleries: ["bees", "ai-art"],
  },
  {
    // "id": 2,
    title: "Bee Science Priestess",
    description: "",
    media: "Virtual pen",
    url: "bees/bee-fancy-wing-0001-scientific-010.jpg",
    width: 1200,
    height: 810,
    slug: "bee-science-priestess",
    hash: "",
    mime: "image/jpeg",
    galleries: ["bees", "ai-art"],
  },
  {
    // "id": 3,
    title: "Bee Study",
    description: " ",
    media: "Ink",
    hash: "",
    mime: "image/jpeg",
    url: "bees/bee-line-a60.jpg",
    width: 1200,
    height: 880,
    slug: "bee-study",
    galleries: ["bees", "ai-art"],
  },
  {
    // "id": 4,
    title: "Inked Bee Study #2",
    description: " ",
    media: "Ink",
    url: "bees/bee-line-f40.jpg",
    hash: "",
    mime: "image/jpeg",
    width: 1200,
    height: 880,
    slug: "inked-bee-study-2",
    galleries: ["bees", "ai-art"],
  },
  {
    // "id": 5,
    title: "Golden Bee Animation",
    description: " ",
    media: "Mixed digital",
    url: "bees/bee-gold-animation.gif",
    hash: "",
    mime: "image/gif",
    width: 688,
    height: 464,
    slug: "golden-bee-animation",
    galleries: ["bees", "animations", "ai-art"],
  },
  {
    // "id": 6,
    title: "Red Bee",
    description: " ",
    media: "Mixed digital",
    url: "bees/small-red-bee.jpg",
    hash: "",
    mime: "image/jpeg",
    width: 888,
    height: 664,
    slug: "red-bee",
    galleries: ["bees", "ai-art"],
  },
  {
    title: "Michael Defeating Satan 1",
    description:
      "Archangel Michael defeating Satan in the style of Mark Rothko",
    media: "Digital",
    url: "angels/michael-defeating-satan-1.jpg",
    hash: "",
    mime: "image/jpeg",
    width: 667,
    height: 1000,
    slug: "michael-defeating-satan-1",
    galleries: ["angels", "ai-art"],
  },
  {
    // id: 63,
    title: "Michael Defeating Satan 2",
    description:
      "Archangel Michael defeating Satan in the style of Mark Rothko",
    media: "Digital",
    url: "angels/michael-defeating-satan-2.jpg",
    hash: "",
    mime: "image/jpeg",
    width: 667,
    height: 1000,
    slug: "michael-defeating-satan-2",
    galleries: ["angels", "ai-art"],
  },
  {
    // id: 64,
    title: "Archangel Michael 1",
    description: "Archangel Michael in the style of Alphonse Mucha",
    media: "Digital",
    url: "angels/michael-archangel-1.jpg",
    hash: "",
    mime: "image/jpeg",
    width: 1000,
    height: 1000,
    slug: "archangel-michael-1",
    galleries: ["angels", "ai-art"],
  },
  {
    // id: 65,
    title: "Archangel Raphael Full of Glory",
    description:
      "Archangel Raphael Full of Glory in the style of Barnett Newman",
    media: "Digital",
    url: "angels/raphael-full-of-glory.jpg",
    hash: "",
    mime: "image/jpeg",
    width: 951,
    height: 1000,
    slug: "archangel-raphael-full-of-glory",
    galleries: ["angels", "ai-art"],
  },
  {
    // id: 66,
    title: "Raphael and the Snake",
    description:
      "Archangel Raphael wrestles a snake in the style of Ad Reinhardt",
    media: "Digital",
    url: "angels/raphael-and-snake.jpg",
    hash: "",
    mime: "image/jpeg",
    width: 951,
    height: 1000,
    slug: "raphael-and-the-snake",
    galleries: ["angels", "ai-art"],
  },
];
